#!/bin/bash

if [ $# == 0 ]
then
	echo "number of argument was 0"
else
	if [ "$1" == "second" ]
	then
		echo "second parameter was "$1""
	else
		echo "number of parameters was $# but it was \"$1\""
	fi
fi

if [ $? == 0 ]
then
	echo "Make successful"
else
	echo "Make not successful"
fi
