#!/bin/bash

getDate() {
	date
	return
}

getDate

name="John"

demLocal() {
	#local means its only available in this function
	local name="Choi"
	return
}

demLocal

echo "$name"

getSum() {
	local num3=$1
	local num4=$2
	
	local sum=$((num3 + num4))

	echo $sum
}

num1=5
num2=6

#passing in parameters
sum=$(getSum num1 num2)
echo "The sum is $sum"
